# .github/workflows/ci-cd.yml
jobs:
    pypi-publish:
        name: Upload release to PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        runs-on: ubuntu-latest
        environment:
            name: pypi
            url: https://pypi.org/p/experimenter
        permissions:
            # IMPORTANT: this permission is mandatory for trusted publishing
            id-token: write  
        steps:
        # retrieve your distributions here      
            - name: Publish package distributions to PyPI
            uses: pypa/gh-action-pypi-publish@release/v1
        
